version: "3.8"

services:
  server:  # Service Backend de l'application
    build: .
    restart: always
    ports:
      - 8080:8080 # L'application backend est exposée sur le port 8080.
    depends_on:
      - mysqldb
    volumes:
      - server-data:/path/in/container

  mysqldb:  # Service MySQL pour la base de données
    platform: linux/x86_64
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: productdb
      MYSQL_USER: mohamed
      MYSQL_PASSWORD: mohamed
      MYSQL_ROOT_PASSWORD: mohamed
    volumes:
      - mysql-data:/var/lib/mysql


  web:  # Service Frontend de l'application
    build: ../Product-frontend
    container_name: product-frontend
    ports:
      - 4200:80 # L'application frontend est exposée sur le port 4200.
    links:
      - server

volumes: # Définition des volumes Docker
  server-data:
  mysql-data: